/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Tharaki Kulathunga
 */
public class TotalComplexity extends javax.swing.JFrame {

    /**
     * Creates new form TotalComplexity
     */
    int Cc = 0;
    int Kw = 0;
    int Cs=0;
    int Cm=0;
    int Cv=0;
    int Ci=0;
    int Ccs=0;
    int Ccp=0;
    long TCps=0;
    public TotalComplexity() {
        initComponents();
        setSize(1350,850);
    }

    public void SetValues(int prCc, int prKw, int prCs,int prCm, int prcv, int prci, int prCcs, int prCcp, long prTCps)
    {
        Cc = prCc;
        Kw = prKw;
        Cs = prCs;
        Cm = prCm;
        Cv = prcv;
        Ci = prci;
        Ccs = prCcs;
        Ccp = prCcp;
        TCps = prTCps;
        
        totcodecomplxity.setText(Integer.toString(Cc));
        totkeyword.setText(Integer.toString(Kw));
        totsize.setText(Integer.toString(Cs));
        totmethod.setText(Integer.toString(Cm));
        totveriable.setText(Integer.toString(Cv));
        totinheritance.setText(Integer.toString(Ci));
        totcontralstru.setText(Integer.toString(Ccs));
        totcoupling.setText(Integer.toString(Ccp));
        
        
        totalTCps.setText(Long.toString(TCps));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totcoupling = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totkeyword = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        totcodecomplxity = new javax.swing.JLabel();
        totsize = new javax.swing.JLabel();
        totmethod = new javax.swing.JLabel();
        totveriable = new javax.swing.JLabel();
        totcontralstru = new javax.swing.JLabel();
        totinheritance = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        totalTCps = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Total Complexity Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Coupling Complexity :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        totcoupling.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totcoupling.setText("--");
        getContentPane().add(totcoupling, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Key-Word Usage :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        totkeyword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totkeyword.setText("--");
        getContentPane().add(totkeyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Code Complexity :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Size Complexity :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Method Complexity :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Veriable Complexity :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Control Stracture Complexity :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Inheritance Complexity :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        totcodecomplxity.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totcodecomplxity.setText("--");
        getContentPane().add(totcodecomplxity, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        totsize.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totsize.setText("--");
        getContentPane().add(totsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        totmethod.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totmethod.setText("--");
        getContentPane().add(totmethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        totveriable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totveriable.setText("--");
        getContentPane().add(totveriable, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        totcontralstru.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totcontralstru.setText("--");
        getContentPane().add(totcontralstru, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        totinheritance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totinheritance.setText("--");
        getContentPane().add(totinheritance, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jLabel68.setText("TCps( Total complexity of a program statement )");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 630, -1));

        totalTCps.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalTCps.setText("--");
        getContentPane().add(totalTCps, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TotalComplexity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TotalComplexity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TotalComplexity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TotalComplexity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TotalComplexity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel totalTCps;
    private javax.swing.JLabel totcodecomplxity;
    private javax.swing.JLabel totcontralstru;
    private javax.swing.JLabel totcoupling;
    private javax.swing.JLabel totinheritance;
    private javax.swing.JLabel totkeyword;
    private javax.swing.JLabel totmethod;
    private javax.swing.JLabel totsize;
    private javax.swing.JLabel totveriable;
    // End of variables declaration//GEN-END:variables
}
